
name: Build and deploy website

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v1
    
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: 🔨 Install Package 
      run: npm install

    - name: Build Project
      run:  npm run build
    
    - name: List output files
      run: find build/ -print

    - name: Sync files
      uses: airvzxf/ftp-deployment-action@latest
      with:
        server: ftp.barmeaashish.com.np
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_dir: "./build/"
        remote_dir: "/public_html/"
      
