
name: Build and deploy website

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  web-deploy:
    name: Deploy
    runs-on: github

    steps:
    - name: Get latest code
      uses: actions/checkout@v1
      
    - name: Sync files
      uses: airvzxf/ftp-deployment-action@latest
      with:
        server: ftp.barmeaashish.com.np
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        remote_dir: "/public_html/"
      
